name: lint_python
on: [push, pull_request]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --count --max-complexity=10 --max-line-length=88 --show-source --statistics

